== Why look beyond investment thesis
****
This section needs to justify the entire book; be extra persuasive as this justifies reading the rest of the book. Here's where we buy attention.
****

[.lead]
I get it.

Every single person that looks at Bitcoin is interested in it's meteoric price appreciation.

Number-go-up. As it's called in Bitcoin circles.

And yes, bitcoin's volatility is all but well-known so you're ready to, as financial planners suggest, "only buy what you're willing to risk" or the less pessimistic "size your exposure according to your risk profile."

This all sounds like sound advice. But is it?

If you look carefully you'll notice the leakage of financial ideas right off the bat.

This is part of the problem.

We've been operating under a monetary system that requires the undoing of one of the most important traits of human civilization: labor specialization. You must know grasp and measure your "risk profile." and size it accordingly. But whatever you do, don't peak under the hood
