= One summer morning in sunny Miami =

"Quick question: should I coinjoin my bitcoins?"

The question completely caught me by off guard.

"eehh, yes. No. Well. Maybe. I don't know."

In hindsight, the answer was obviously a nuanced "MAYBE!" but who was asking the question dumbfunded me.

Adrian was my canadian friend and neighbor in Costa Rica, whom I had accidentally orange-pilled over many afternoons hanging-out by the pool.

*Thank you, eternal Costa Rican summer.*

He came up to speed on the importance of bitcoin like a thunder. From most people's default of *"bitcoin is a joke"* to *"oh-my-god-I-must-dedicate-my-life-to-creating-a-bright-orange-future-for-my-children!"*

Within months of starting to acquire as much bitcoin as he possibly could he had spent some of his dry-powder to fly to Bitcoin 2022.

"So, should I coinjoin or not?", he repeated impatiently -- we were standing in one of the crowded hallways at the conference and, I'm guessing, he could see my dropped-jaw was not about to emit any astute advice.

Clearly he had gone to a talk about on-chain privacy and was eager to do things *the right way*.

To put things in perspective, I knew for a fact he had done he's very first bitcoin transaction a few days ago. I know, I helped him do it.

At that very moment I knew I had to write this book.

### Who this book is for
This book is likely for you. If you are relatively new to bitcoin, you might have read one of those fabulous books that posit the investment-thesis for Bitcoin.

"The Bitcoin Standard" by Saifadean Ammous.

Or perhaps even the shorter "The bullish case for Bitcoin" by Va... (the one that pushed Adrian over the orange cliff)

These books make a strong case for the *why* of owning bitcoin.

This book attempts to explain the *how*, and, more importantly, through the *how* to use bitcoin, guide the path towards truly understanding what bitcoin is.

And if you are anything like me and the hundreds of people I've helped *use* bitcoin, using bitcoin might lead you to some very interesting and, perhaps, metaphysical conclusions about the nature of money, value, wealth and languages.

### Why understanding how to use bitcoin is fundamnetal for the investment thesis
I get it.

Every single person that looks at Bitcoin is interested in it's meteoric price appreciation.

Number-go-up. As it's called in Bitcoin circles.

And yes, bitcoin's volatility is all but well-known so you're ready to, as financial planners suggest, "only buy what you're willing to risk" or the less pessimistic "size your exposure according to your risk profile."

This all sounds like sound advice. But is it?

If you look carefully you'll notice the leakage of financial ideas right off the bat.

This is part of the problem.

We've been operating under a monetary system that requires the undoing of one of the most important traits of human civilization: labor specialization. You must know grasp and measure your "risk profile." and size it accordingly. But whatever you do, don't 

## How this book is organized
There's a natural progression of needs and wants on the bitcoiner/hero's journey. Each layer builds on top of the previous one, like a pyramid.

Let's call it...
